#!/bin/bash

---
- name: Remove Current Deluge container
  docker_container:
    name: deluge
    state: absent

- name: Initialize Folders Deluge
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/deluge

- name: Pull container and Initialize
  docker_container:
    name: deluge
    image: "lsioarmhf/deluge"
    pull: yes
    published_ports:
      - "0.0.0.0:8112:8112"
      - "58846:58846"
      - "58946:58946"
    env:
      APP: "deluge"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "1000"
      PGID: "1000"
      MONO_TLS_PROVIDER: legacy
    networks:
      - name: armada
        aliases:
          - "deluge"
    volumes:
      - "/mnt:/mnt"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started

