#!/bin/bash

---
- name: Remove Current Ombi container
  docker_container:
    name: ombi
    state: absent

- name: Initialize Folders Ombi
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/ombi

- name: Pull container and Initialize
  docker_container:
    name: ombi
    image: "lsioarmhf/ombi"
    pull: yes
    published_ports:
      - "0.0.0.0:3579:3579"
    env:
      APP: "ombi"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "1000"
      PGID: "1000"
      MONO_TLS_PROVIDER: legacy
    networks:
      - name: armada
        aliases:
          - "ombi"
    volumes:
      - "/mnt:/mnt"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started

