#!/bin/bash

---
- name: Remove Current jackett container
  docker_container:
    name: jackett
    state: absent

- name: Initialize Folders jackett
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/jackett

- name: Pull container and Initialize
  docker_container:
    name: jackett
    image: "lsioarmhf/jackett"
    pull: yes
    published_ports:
      - "0.0.0.0:9117:9117"
    env:
      APP: "jackett"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "1000"
      PGID: "1000"
      MONO_TLS_PROVIDER: legacy
    networks:
      - name: armada
        aliases:
          - "jackett"
    volumes:
      - "/mnt:/mnt"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started

